### ISSUE TITLE
Реализовать  перегрузку операторов через "функцию"

### ISSUE THREAD

**Issue by Jrol123** [Jrol123/IMKT-FEFU#29]
`__contains__` должна отсылать к `contains`, и т. д..
Это нужно для более интуитивного использования функций

**Comment by Jrol123** [comment]
@Tyferse, мы явное через неявное задаём или наоборот?

**Comment by Tyferse** [comment]
Явное - лучше, чем неявное. Это один из главных постулатов Python-а. Потому, перегрузку оператора `in` я бы не делал.

> @Tyferse, мы явное через неявное задаём или наоборот?
