### ISSUE TITLE
Построить Bounded Plane

### ISSUE THREAD

**Issue by Jrol123** [Jrol123/IMKT-FEFU#30]
Bounded Plane - ограниченная плоскость
Возможные Методы:

1. Определить наименьший угол между OX / OY / OZ и нормалью
2. Повернуть "vs" так, чтобы OX / OY / OZ совпадали с нормалью
3. Повернуть оставшиеся 2 координаты по 2-м углам.
4. Домножить 2 координаты на width и height

**ИЛИ**

1. сопоставить всю систему "vs" с нормалью, где OZ = vector_normal
2. Прокрутить OX на alpha_1, OY на alpha_2
3. Умножить OX на width, OY на height

**ИЛИ**

1. На вход получается точка, нормаль, направляющий вектор и угол
  1.1. Направляющий вектор должен быть нормализован и лежать на плоскости
2. Строим правую тройку векторов. Можно сразу же умножать вектора на длину и ширину
3. Поворачиваем побочный вектор на alpha
Стоп, а это не просто улучшенная версия моего способа??

Список проблем:
1. Если работать с "наименьшим углом", то как определить, какую штуку на что прокручивать + умножение?
2. Если работать с OZ = vector_normal, то нужно понять, в какую сторону поворачивать
Доп:
1. учесть, что угол между "побочными" векторами может быть не прямым (ромбы) =>
2. поворот идёт сразу по всем осям (и относительно осей) => разбить поворот на 3 части (OX, OY, OZ).
   Можно поворачивать по-очереди.

Возможно, @Tyferse может помочь

**Comment by Tyferse** [comment]
> 4. поворот идёт сразу по всем осям (и относительно осей) => разбить поворот на 3 части (OX, OY, OZ).
Можно поворачивать по-очереди.
#
Это пока что единственное, что я считаю приемлемым для реализации. Но нужен класс Parameters. Именно там (оказывается), нужно реализовать поворот, перемещение и масштабирование.

**Comment by Jrol123** [comment]
> > 4. поворот идёт сразу по всем осям (и относительно осей) => разбить поворот на 3 части (OX, OY, OZ).
> >    Можно поворачивать по-очереди.
> 
> Это пока что единственное, что я считаю приемлемым для реализации. Но нужен класс Parameters. Именно там (оказывается), нужно реализовать поворот, перемещение и масштабирование.

Тоже пока только это сделал
