### ISSUE TITLE
Автоматическое создание объектов и помещение их в `Map`

### ISSUE THREAD

**Issue by Jrol123** [Jrol123/IMKT-FEFU#36]
Можно сразу же создавать объекты в `Map`, но стоит ли это делать?
Стоит ли отдельно делать `Map` кубов, сфер и т. д.?
@Tyferse, как думаешь?

**Comment by Tyferse** [comment]
Не понимаю, что ты имеешь в виду под созданием объектов в `Map`. Это же по своей задумке просто список объектов, который по другому называется. Если нет - переубеди меня.
